//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_AMEEN_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class bm000
    {
        public string Name { get; set; }
        public System.Guid GUID { get; set; }
    }
}
