//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_AMEEN_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatExBarcode000
    {
        public System.Guid Guid { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.Guid> MatGuid { get; set; }
        public Nullable<int> MatUnit { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public string Notes { get; set; }
    }
}
