//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_AMEEN_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmnDb001Entities2 : DbContext
    {
        public AmnDb001Entities2()
            : base("name=AmnDb001Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bm000> bm000 { get; set; }
        public virtual DbSet<gr000> gr000 { get; set; }
        public virtual DbSet<MatExBarcode000> MatExBarcode000 { get; set; }
        public virtual DbSet<mh000> mh000 { get; set; }
        public virtual DbSet<mt000> mt000 { get; set; }
        public virtual DbSet<my000> my000 { get; set; }
    }
}
