//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_AMEEN_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class mh000
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> CurrencyGUID { get; set; }
        public Nullable<double> CurrencyVal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
