//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_AMEEN_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt000
    {
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string LatinName { get; set; }
        public string BarCode { get; set; }
        public string CodedCode { get; set; }
        public string Unity { get; set; }
        public string Spec { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Whole { get; set; }
        public Nullable<double> Half { get; set; }
        public Nullable<double> Retail { get; set; }
        public Nullable<double> EndUser { get; set; }
        public Nullable<double> Export { get; set; }
        public Nullable<double> Vendor { get; set; }
        public Nullable<double> MaxPrice { get; set; }
        public Nullable<double> AvgPrice { get; set; }
        public Nullable<double> LastPrice { get; set; }
        public Nullable<int> PriceType { get; set; }
        public Nullable<int> SellType { get; set; }
        public Nullable<double> BonusOne { get; set; }
        public Nullable<double> CurrencyVal { get; set; }
        public Nullable<double> UseFlag { get; set; }
        public string Origin { get; set; }
        public string Company { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Security { get; set; }
        public Nullable<System.DateTime> LastPriceDate { get; set; }
        public Nullable<double> Bonus { get; set; }
        public string Unit2 { get; set; }
        public Nullable<double> Unit2Fact { get; set; }
        public string Unit3 { get; set; }
        public Nullable<double> Unit3Fact { get; set; }
        public Nullable<double> Flag { get; set; }
        public string Pos { get; set; }
        public string Dim { get; set; }
        public Nullable<bool> ExpireFlag { get; set; }
        public Nullable<bool> ProductionFlag { get; set; }
        public Nullable<bool> Unit2FactFlag { get; set; }
        public Nullable<bool> Unit3FactFlag { get; set; }
        public string BarCode2 { get; set; }
        public string BarCode3 { get; set; }
        public Nullable<bool> SNFlag { get; set; }
        public Nullable<bool> ForceInSN { get; set; }
        public Nullable<bool> ForceOutSN { get; set; }
        public Nullable<double> VAT { get; set; }
        public string Color { get; set; }
        public string Provenance { get; set; }
        public string Quality { get; set; }
        public string Model { get; set; }
        public Nullable<double> Whole2 { get; set; }
        public Nullable<double> Half2 { get; set; }
        public Nullable<double> Retail2 { get; set; }
        public Nullable<double> EndUser2 { get; set; }
        public Nullable<double> Export2 { get; set; }
        public Nullable<double> Vendor2 { get; set; }
        public Nullable<double> MaxPrice2 { get; set; }
        public Nullable<double> LastPrice2 { get; set; }
        public Nullable<double> Whole3 { get; set; }
        public Nullable<double> Half3 { get; set; }
        public Nullable<double> Retail3 { get; set; }
        public Nullable<double> EndUser3 { get; set; }
        public Nullable<double> Export3 { get; set; }
        public Nullable<double> Vendor3 { get; set; }
        public Nullable<double> MaxPrice3 { get; set; }
        public Nullable<double> LastPrice3 { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> GroupGUID { get; set; }
        public Nullable<System.Guid> PictureGUID { get; set; }
        public Nullable<System.Guid> CurrencyGUID { get; set; }
        public Nullable<int> DefUnit { get; set; }
        public Nullable<bool> bHide { get; set; }
        public Nullable<long> branchMask { get; set; }
        public Nullable<System.Guid> OldGUID { get; set; }
        public Nullable<System.Guid> NewGUID { get; set; }
        public Nullable<bool> Assemble { get; set; }
        public Nullable<double> OrderLimit { get; set; }
        public Nullable<bool> CalPriceFromDetail { get; set; }
        public Nullable<bool> ForceInExpire { get; set; }
        public Nullable<bool> ForceOutExpire { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsIntegerQuantity { get; set; }
        public Nullable<bool> ClassFlag { get; set; }
        public Nullable<bool> ForceInClass { get; set; }
        public Nullable<bool> ForceOutClass { get; set; }
        public Nullable<bool> DisableLastPrice { get; set; }
        public Nullable<double> LastPriceCurVal { get; set; }
        public Nullable<double> PrevQty { get; set; }
        public Nullable<System.DateTime> FirstCostDate { get; set; }
        public Nullable<bool> IsCalcTaxForPUTaxCode { get; set; }
        public Nullable<bool> HasSegments { get; set; }
        public Nullable<System.Guid> Parent { get; set; }
        public Nullable<bool> IsCompositionUpdated { get; set; }
        public Nullable<bool> InheritsParentSpecs { get; set; }
        public string CompositionName { get; set; }
        public string CompositionLatinName { get; set; }
        public Nullable<double> LastPriceWithDiscAndExtra { get; set; }
        public string ExemptionReasonCode { get; set; }
        public string GPC { get; set; }
    }
}
