//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_AMEEN_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class my000
    {
        public Nullable<int> Number { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<double> CurrencyVal { get; set; }
        public string PartName { get; set; }
        public Nullable<int> PartPrecision { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Security { get; set; }
        public string LatinName { get; set; }
        public string LatinPartName { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<long> branchMask { get; set; }
        public Nullable<System.Guid> PictureGUID { get; set; }
        public string CurrencyISO { get; set; }
    }
}
